import type { Language } from "./types";

/**
 * Word pools for the non-English languages. Each list is a few hundred of the
 * most common words in that language, lowercase, with the native diacritics
 * kept. Typing them on a US layout will throw errors on the accented keys, and
 * that is on purpose: the key heatmap will show exactly which ones.
 *
 * The two English pools live in words.ts (they predate this file and feed the
 * daily challenge seed, so they are left where they are).
 */

const SPANISH = `de la que el en y a los del se las por un para con no una su al lo como más pero sus le ya o este sí porque esta entre cuando muy sin sobre también me hasta hay donde quien desde todo nos durante todos uno les ni contra otros ese eso ante ellos e esto mí antes algunos qué unos yo otro otras otra él tanto esa estos mucho quienes nada muchos cual poco ella estar estas algunas algo nosotros mi mis tú te ti tu tus ellas nosotras vosotros vosotras os mío mía míos mías tuyo tuya tuyos tuyas suyo suya suyos suyas nuestro nuestra nuestros nuestras vuestro vuestra vuestros vuestras esos esas estoy estás está estamos están esté estés estemos estén estaré estarás estará estaremos estarán estaría estarías estaríamos estarían estaba estabas estábamos estaban estuve estuviste estuvo estuvimos estuvieron he has ha hemos han haya hayas hayamos hayan habré habrás habrá habremos habrán había habías habíamos habían soy eres es somos son sea seas seamos sean seré serás será seremos serán sería serías seríamos serían era eras éramos eran fui fuiste fue fuimos fueron tengo tienes tiene tenemos tienen tenga tengas tengamos tengan tendré tendrás tendrá tendremos tendrán tenía tenías teníamos tenían casa tiempo vida hombre mundo día año trabajo parte forma manera lugar caso momento agua palabra cosa ejemplo país historia punto mano gobierno grupo nombre problema idea mujer nivel número persona programa cuestión gente sistema fin ciudad hijo verdad familia noche estado mes libro puerta plan luz color pueblo campo obra causa cuerpo tierra centro medio proceso ser hacer poder decir ir ver dar saber querer llegar pasar deber poner parecer quedar creer hablar llevar dejar seguir encontrar llamar venir pensar salir volver tomar conocer vivir sentir tratar mirar contar empezar esperar buscar existir entrar trabajar escribir perder producir ocurrir recordar terminar permitir aparecer conseguir comenzar servir sacar necesitar mantener resultar leer caer cambiar presentar crear abrir considerar oír recibir grande mismo nuevo bueno alto español primero mayor último gran menor mejor peor pequeño malo joven largo bajo importante general blanco negro rojo verde azul mucho poco todo cada tanto demasiado nada algo bien mal aquí allí ahora antes después siempre nunca hoy mañana ayer entonces luego mientras además tampoco tan menos casi solo sólo así bastante quizás acaso`
  .split(/\s+/)
  .filter(Boolean);

const FRENCH = `le de un à être et en avoir que pour dans ce il qui ne sur se pas plus pouvoir par je avec tout faire son mettre autre on mais nous comme ou si leur y dire elle devoir avant deux même prendre aussi celui donner bien où fois vous encore nouveau aller cela entre premier vouloir déjà grand mon me trop très savoir falloir voir quelque sans raison notre dont non an monde jour monsieur demander alors après trouver personne rendre part dernier venir pendant passer peu lequel suite bon comprendre depuis point ainsi heure rester tenir femme paraître besoin cas moment sembler enfant chose là point homme mer dieu contre elles avez quel oui non peut-être plein terre eau feu vent maison ville nom lettre mère père fils tête main coeur temps vie amour nuit matin soir semaine mois année travail pays histoire exemple raison question groupe partie manière endroit corps esprit force lumière couleur voix chemin fenêtre porte suis es est sommes êtes sont sois soit soyons soyez soient serai seras sera serons serez seront serais serait serions seriez seraient étais était étions étiez étaient fus fut fûmes furent ai as a avons avez ont aie aies ait ayons ayez aient aurai auras aura aurons aurez auront aurais aurait aurions auriez auraient avais avait avions aviez avaient eus eut eûmes eurent vais vas va allons allez vont aille ailles allions alliez aillent irai iras ira irons irez iront irais irait irions iriez iraient allais allait allions alliez allaient fais fait faisons faites font fasse fasses fassions fassiez fassent ferai feras fera ferons ferez feront ferais ferait ferions feriez feraient faisais faisait faisions faisiez faisaient beau bon petit vieux grand jeune long haut bas nouveau premier dernier autre même tel quel tout chaque plusieurs certain aucun blanc noir rouge vert bleu jaune gris important général possible vrai faux plein vide chaud froid fort faible ici maintenant hier aujourd'hui demain toujours jamais souvent parfois encore déjà bientôt tard tôt vite lentement ensemble seul dehors dedans dessus dessous devant derrière loin près assez trop peu beaucoup moins plus très bien mal presque seulement pourtant cependant ainsi donc alors puis quand comme parce`
  .split(/\s+/)
  .filter(Boolean);

const GERMAN = `der die und in den von zu das mit sich des auf für ist im dem nicht ein eine als auch es an werden aus er hat dass sie nach wird bei einer um am sind noch wie einem über einen so zum war haben nur oder aber vor zur bis mehr durch man sein wurde sei stadt jahr welt tag mann leben frau kind haus land teil weg fall zeit hand auge kopf herz wort buch tür licht farbe stimme grund arbeit ende seite platz mensch gruppe frage stunde beispiel geschichte name nummer person system programm problem idee wasser feuer wind erde stein baum weg straße morgen abend nacht woche monat vater mutter sohn tochter freund bruder schwester ich du wir ihr mir mich dir dich uns euch ihm ihn ihnen ihrer meiner deiner unser euer mein dein sein unser euer dieser jener jeder aller kein manch solch welch beide viele wenige einige andere selbe ganz halb bin bist ist sind seid war warst waren wart gewesen werde wirst wird werden werdet wurde wurdest wurden wurdet geworden habe hast hat haben habt hatte hattest hatten hattet gehabt kann kannst können könnt konnte konnten muss musst müssen müsst musste mussten will willst wollen wollt wollte wollten soll sollst sollen sollt sollte sollten darf darfst dürfen dürft durfte durften mag magst mögen mögt mochte mochten gehen gehe gehst geht ging gingen kommen komme kommst kommt kam kamen sehen sehe siehst sieht sah sahen geben gebe gibst gibt gab gaben finden finde findest findet fand fanden nehmen nehme nimmst nimmt nahm nahmen groß klein alt jung neu gut schlecht hoch tief lang kurz weit nah schnell langsam stark schwach schön hässlich wichtig ganz voll leer warm kalt hell dunkel weiß schwarz rot grün blau gelb grau hier dort jetzt heute gestern morgen immer nie oft manchmal schon noch bald spät früh zusammen allein oben unten vorne hinten links rechts weit nah genug zu wenig viel mehr weniger sehr gut schlecht fast nur aber doch also dann wenn weil dass damit obwohl während`
  .split(/\s+/)
  .filter(Boolean);

const ITALIAN = `di che e la il un a per in non una mi si ho ma lo ti le ci se cosa io sono ha come qui questo tutto bene lei della del quello me più quando anche o da noi voi loro suo mio tuo nostro vostro questa quella questi quelle quei quegli chi cui dove perché mentre dopo prima senza sotto sopra tra fra contro verso oltre casa tempo vita uomo mondo giorno anno lavoro parte modo luogo caso momento acqua parola cosa esempio paese storia punto mano governo gruppo nome problema idea donna livello numero persona programma questione gente sistema fine città figlio verità famiglia notte stato mese libro porta luce colore popolo campo opera corpo terra centro mezzo essere avere fare dire andare potere volere sapere dovere vedere dare stare venire parlare trovare sentire lasciare prendere guardare chiamare portare tornare passare credere tenere restare vivere pensare uscire aprire chiudere mettere conoscere capire aspettare cercare arrivare diventare cominciare finire ricordare riuscire sembrare rimanere scrivere leggere perdere seguire nascere morire vincere sono sei è siamo siete sono sia siamo siate siano sarò sarai sarà saremo sarete saranno sarei saresti sarebbe saremmo sareste sarebbero ero eri era eravamo eravate erano fui fosti fu fummo foste furono ho hai ha abbiamo avete hanno abbia abbiamo abbiate abbiano avrò avrai avrà avremo avrete avranno avrei avresti avrebbe avremmo avreste avrebbero avevo avevi aveva avevamo avevate avevano ebbi avesti ebbe avemmo aveste ebbero grande piccolo nuovo vecchio buono cattivo alto basso lungo corto bello brutto giovane primo ultimo stesso altro molto poco tutto ogni tanto troppo niente qualcosa bene male qui lì ora prima dopo sempre mai spesso ancora già presto tardi insieme solo fuori dentro sopra sotto davanti dietro lontano vicino abbastanza troppo poco molto meno più assai quasi soltanto però tuttavia così dunque allora poi quando come perché siccome`
  .split(/\s+/)
  .filter(Boolean);

const PORTUGUESE = `de a o que e do da em um para com não uma os no se na por mais as dos como mas ao ele das à seu sua ou quando muito nos já eu também só pelo pela até isso ela entre depois sem mesmo aos seus quem nas me esse eles você essa num nem suas meu às minha numa pelos elas qual será nós lhe deles essas esses pelas este dele tu te vós vos teu tua teus tuas nosso nossa nossos nossas vosso vossa isto aquilo estes estas aquele aquela aqueles aquelas casa tempo vida homem mundo dia ano trabalho parte forma maneira lugar caso momento água palavra coisa exemplo país história ponto mão governo grupo nome problema ideia mulher nível número pessoa programa questão gente sistema fim cidade filho verdade família noite estado mês livro porta luz cor povo campo obra corpo terra centro meio ser estar ter fazer dizer ir ver dar saber querer poder chegar passar dever pôr parecer ficar crer falar levar deixar seguir encontrar chamar vir pensar sair voltar tomar conhecer viver sentir tratar olhar contar começar esperar buscar existir entrar trabalhar escrever perder produzir ocorrer lembrar terminar permitir aparecer conseguir servir tirar precisar manter resultar ler cair mudar apresentar criar abrir considerar ouvir receber sou és é somos sois são seja sejas sejamos sejam serei serás será seremos serão seria serias seríamos seriam era eras éramos eram fui foste foi fomos foram tenho tens tem temos têm tenha tenhas tenhamos tenham terei terás terá teremos terão teria terias teríamos teriam tinha tinhas tínhamos tinham grande pequeno novo velho bom mau alto baixo longo curto bonito feio jovem primeiro último outro mesmo muito pouco todo cada tanto demais nada algo bem mal aqui ali agora antes depois sempre nunca hoje amanhã ontem então logo enquanto além tampouco tão menos quase apenas assim bastante talvez`
  .split(/\s+/)
  .filter(Boolean);

// Roman Urdu: Urdu written in the Latin alphabet, which is how most Urdu is
// typed on a physical keyboard. Native Nastaliq script would need right to left
// support across the word stream and caret, so that is a separate piece of work.
const ROMAN_URDU = `main mein hum tum aap woh yeh wo ye kya kyun kaise kahan kab kaun kitna kitni is us in un ka ke ki ko se par pe tak ne hi bhi to na nahi haan ji acha theek bohat bahut thora zyada kam sab kuch koi sara poora aadha ek do teen char paanch che saat aur ya lekin magar phir jab tab agar warna kyunke taake jaise waise itna utna aisa waisa yahan wahan abhi kabhi hamesha roz aaj kal parson subah shaam raat din dopahar waqt der jaldi ab pehle baad andar bahar upar niche aage piche saamne pas door bilkul shayad zaroor beshak sach jhoot hona karna jana aana dena lena kehna sunna dekhna parhna likhna bolna chalna daurna baithna uthna sona jagna khana peena banana todna kholna band rakhna uthana girana milna khona samajhna sochna chahna umeed intezaar shuru khatam ho hai hain tha thi the hoga hogi honge kar karo kiya kiye karunga karungi karenge gaya gayi gaye raha rahi rahe ghar kaam log dost dushman pyaar mohabbat zindagi duniya dil dimagh jaan haath pair sar aankh muh baal khoon paani aag hawa zameen aasman suraj chaand sitara mausam baarish garmi sardi shehar gaon rasta darwaza khidki kitab qalam roshni rang qaum aurat mard bacha bachi ladka ladki insaan bhai behen maa baap beta beti nana nani dada dadi chacha mama khala phupu family shaadi khushi gham dard mushkil aasan naya purana bara chota lamba mota patla khubsurat pyara accha bura sahi ghalat sacha jhoota andhera ujala thanda garam meetha kadwa namkeen safed kaala laal hara neela peela zard bhura khali bhara mera tera uska hamara tumhara unka apna kisi sabke`
  .split(/\s+/)
  .filter(Boolean);

export const LANGUAGE_POOLS: Partial<Record<Language, string[]>> = {
  spanish: SPANISH,
  french: FRENCH,
  german: GERMAN,
  italian: ITALIAN,
  portuguese: PORTUGUESE,
  "roman-urdu": ROMAN_URDU,
};

export const LANGUAGES: { id: Language; label: string }[] = [
  { id: "english", label: "English" },
  { id: "english-1k", label: "English wide" },
  { id: "spanish", label: "Spanish" },
  { id: "french", label: "French" },
  { id: "german", label: "German" },
  { id: "italian", label: "Italian" },
  { id: "portuguese", label: "Portuguese" },
  { id: "roman-urdu", label: "Urdu (Roman)" },
];
